name: 'Upload artifact'

description: 'Action for uploading an artifact'

inputs:
  name:
    description: 'Name of the artifact'
    required: true
    default: 'artifact'
  path:
    description: 'Path to the artifact'
    required: true

runs:
  using: "composite"

  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
