name: 'Upload artifact'

description: 'Action for uploading an artifact'

inputs:
  name:
    description: 'Name of the artifact'
    required: true
    default: 'artifact'
  path:
    description: 'Path to the artifact'
    required: true

runs:
  using: "composite"

  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@89ef406dd8d7e03cfd12d9e0a4a378f454709029 # v4.3.5
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
