name: 'Upload artifact'

description: 'Action for uploading an artifact'

inputs:
  name:
    description: 'Name of the artifact'
    required: true
    default: 'artifact'
  path:
    description: 'Path to the artifact'
    required: true

runs:
  using: "composite"

  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
