name: 'Upload artifact'

description: 'Action for uploading an artifact'

inputs:
  name:
    description: 'Name of the artifact'
    required: true
    default: 'artifact'
  path:
    description: 'Path to the artifact'
    required: true

runs:
  using: "composite"

  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
