name: 'Upload artifact'

description: 'Action for uploading an artifact'

inputs:
  name:
    default: 'artifact'
    description: 'Name of the artifact'
    required: true
    type: string
  path:
    description: 'Path to the artifact'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
