name: 'Upload artifact'

description: 'Action for uploading an artifact'

inputs:
  name:
    description: 'Name of the artifact'
    required: true
    default: 'artifact'
  path:
    description: 'Path to the artifact'
    required: true

runs:
  using: "composite"

  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4.4.1
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
