name: 'Setup Xcode'

description: 'Action for setting up Xcode'

inputs:
  xcode-version:
    description: 'Xcode version'
    required: true
    default: '13.4.1'

runs:
  using: "composite"

  steps:
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1
      if: matrix.os == 'macos-latest'
      with:
        xcode-version: ${{ inputs.xcode-version }}
