name: 'Setup Python'

description: 'Action for setting up Python'

inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.10'

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
      with:
        python-version: ${{ inputs.python-version }}
