name: 'Setup Python'

description: 'Action for setting up Python'

inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.10'

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
      with:
        python-version: ${{ inputs.python-version }}
