name: 'Setup Python'

description: 'Action for setting up Python'

inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.10'

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
      with:
        python-version: ${{ inputs.python-version }}
