name: 'Setup Python'

description: 'Action for setting up Python'

inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.10'

runs:
  using: "composite"

  steps:
    - name: Set up Python
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5
      with:
        python-version: ${{ inputs.python-version }}
