name: 'Checkout'

description: 'Action for checking out a repo'

inputs:
  fetch-depth:
    description: 'Depth for fetching'
    required: true
    default: '0'
  token:
    description: 'GitHub personal authentication token'
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
