name: 'Checkout'

description: 'Action for checking out a repo'

inputs:
  fetch-depth:
    description: 'Depth for fetching'
    required: true
    default: '0'
  token:
    description: 'GitHub personal authentication token'
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
