name: 'Auto Approve'

description: 'Action to auto approve a pull request'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  pull-request-number:
    description: 'Pull request number'
    required: true
  review-message:
    description: 'Review message'
    required: true
    default: 'Auto approved'

runs:
  using: "composite"

  steps:
    - name: Auto Approve
      uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
      with:
        github-token: ${{ inputs.github-token }}
        pull-request-number: ${{ inputs.pull-request-number }}
        review-message: ${{ inputs.review-message }}
