name: 'Upload SARIF'

description: 'Upload SARIF file'

inputs:
  sarif_file:
    description: 'Path to SARIF file'
    required: true

runs:
  using: "composite"

  steps:
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@e5f05b81d5b6ff8cfa111c80c22c5fd02a384118 # v3
      with:
        sarif_file: ${{ inputs.sarif_file }}
