name: 'Upload SARIF'

description: 'Upload SARIF file'

inputs:
  sarif_file:
    description: 'Path to SARIF file'
    required: true

runs:
  using: "composite"

  steps:
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@29d86d22a34ea372b1bbf3b2dced2e25ca6b3384 # v3
      with:
        sarif_file: ${{ inputs.sarif_file }}
