name: 'Find Pull Request'

description: 'Action to find a pull request'

inputs:
  branch:
    description: 'Branch name'
    required: true

outputs:
  number:
    description: "Pull request number"
    value: ${{ steps.find-pull-request.outputs.number }}

runs:
  using: "composite"

  steps:
    - name: Find Pull Request
      id: find-pull-request
      uses: juliangruber/find-pull-request-action@48b6133aa6c826f267ebd33aa2d29470f9d9e7d0 # v1.9.0
      with:
        branch: ${{ inputs.branch }}
