name: 'Find Pull Request'

description: 'Action to find a pull request'

inputs:
  branch:
    description: 'Branch name'
    required: true

outputs:
  number:
    description: "Pull request number"
    value: ${{ steps.find-pull-request.outputs.number }}

runs:
  using: "composite"

  steps:
    - name: Find Pull Request
      id: find-pull-request
      uses: juliangruber/find-pull-request-action@51c53b26c62091a3b00109116b4f239bb65dba87 # v1.8.1
      with:
        branch: ${{ inputs.branch }}
