name: 'Kotlin Native Cache'

description: 'Action for Kotlin Native Cache'

runs:
  using: "composite"

  steps:
    - name: Kotlin native cache
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-konan-${{ hashFiles('**/gradle/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-konan-
