name: 'Kotlin Native Cache'

description: 'Action for Kotlin Native Cache'

inputs:
  cache-enabled:
    description: 'Cache enabled'
    required: true
    default: 'false'

runs:
  using: "composite"

  steps:
    - name: Kotlin native cache
      if: ${{ inputs.cache-enabled == 'true' || inputs.cache-enabled == true }}
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-konan-${{ hashFiles('**/gradle/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-konan-
