name: 'Commit'

description: 'Commit'

inputs:
  commit-message:
    description: 'Commit message'
    required: true
  push:
    description: 'Push changes'
    required: false
    default: 'false'

runs:
  using: "composite"

  steps:
    - name: Commit
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff
        git add .
        git commit -m "${{ inputs.commit-message }}" -a

    - name: Push
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: git push
