name: 'Commit'

description: 'Commit'

inputs:
  commit-message:
    description: 'Commit message'
    required: true

runs:
  using: "composite"

  steps:
    - name: Commit
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff
        git add .
        git commit -m "${{ inputs.commit-message }}" -a
