name: 'Setup Java'

description: 'Action for setting up Java'

inputs:
  distribution:
    description: 'Distribution'
    required: true
    default: 'zulu'
  java-version:
    description: 'Java version'
    required: true
    default: '17'

runs:
  using: "composite"

  steps:
    - name: Set up Java
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
