name: 'Setup Java'

description: 'Action for setting up Java'

inputs:
  distribution:
    description: 'Distribution'
    required: true
    default: 'zulu'
  java-version:
    description: 'Java version'
    required: true
    default: '17'

runs:
  using: "composite"

  steps:
    - name: Set up Java
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
