name: 'Setup Java'

description: 'Action for setting up Java'

inputs:
  distribution:
    description: 'Distribution'
    required: true
    default: 'zulu'
  java-version:
    description: 'Java version'
    required: true
    default: '17'

runs:
  using: "composite"

  steps:
    - name: Set up Java
      uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}
