name: 'Setup Gradle'

description: 'Action for setting up Gradle'

inputs:
  cache-enabled:
    description: 'Gradle cache'
    required: true
    default: 'true'
  cache-encryption-key:
    description: 'Cache encryption key'
    required: true
    default: ''
  gradle-home-cache-cleanup:
    description: 'Cleanup Gradle home cache'
    required: true
    default: 'true'

runs:
  using: "composite"

  steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@db19848a5fa7950289d3668fb053140cf3028d43 # v3
      with:
        cache-disabled: ${{ inputs.cache-enabled == 'false' || inputs.cache-enabled == false }}
        cache-encryption-key: ${{ inputs.cache-encryption-key }}
        gradle-home-cache-cleanup: ${{ inputs.gradle-home-cache-cleanup == 'true' || inputs.gradle-home-cache-cleanup == true }}
        validate-wrappers: true
