name: 'Setup Gradle'

description: 'Action for setting up Gradle'

inputs:
  cache-enabled:
    description: 'Gradle cache'
    required: true
    default: 'true'
  gradle-home-cache-cleanup:
    description: 'Cleanup Gradle home cache'
    required: true
    default: 'true'

runs:
  using: "composite"

  steps:
    - name: Setup Gradle
      uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2.10.0
      with:
        cache-disabled: ${{ inputs.cache-enabled == 'false' || inputs.cache-enabled == false }}
        gradle-home-cache-cleanup: ${{ inputs.gradle-home-cache-cleanup == 'true' || inputs.gradle-home-cache-cleanup == true }}
