name: 'Setup Gradle'

description: 'Action for setting up Gradle'

inputs:
  cache-enabled:
    description: 'Gradle cache'
    required: true
    default: 'true'
  gradle-home-cache-cleanup:
    description: 'Cleanup Gradle home cache'
    required: true
    default: 'true'

runs:
  using: "composite"

  steps:
    - name: Setup Gradle
      uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2 # v2.11.1
      with:
        cache-disabled: ${{ inputs.cache-enabled == 'false' || inputs.cache-enabled == false }}
        gradle-home-cache-cleanup: ${{ inputs.gradle-home-cache-cleanup == 'true' || inputs.gradle-home-cache-cleanup == true }}
