name: 'Setup Gradle'

description: 'Action for setting up Gradle'

inputs:
  cache-enabled:
    description: 'Gradle cache'
    required: true
    default: 'true'
  cache-encryption-key:
    description: 'Cache encryption key'
    required: true
    default: ''
  cache-cleanup:
    description: 'Cleanup Gradle home cache'
    required: true
    default: 'on-success'

runs:
  using: "composite"

  steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@cc4fc85e6b35bafd578d5ffbc76a5518407e1af0 # v4
      with:
        cache-disabled: ${{ inputs.cache-enabled == 'false' || inputs.cache-enabled == false }}
        cache-encryption-key: ${{ inputs.cache-encryption-key }}
        cache-cleanup: ${{ inputs.cache-cleanup }}
        validate-wrappers: true
