name: 'Build and push Docker images'

runs:
  using: "composite"

  steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
