name: 'Qodana'

description: 'Action for running Qodana'

inputs:
  cache-default-branch-only:
    description: 'Cache only default branch'
    required: true
    default: 'true'
  upload-result:
    description: 'Upload Qodana results'
    required: true
    default: 'false'

runs:
  using: "composite"

  steps:
    - name: Qodana Cloud enabled
      if: ${{ startsWith(env.QODANA_TOKEN, 'ey') }}
      shell: bash
      run: echo "Qodana Cloud enabled"

    - name: Running Qodana only locally
      if: ${{ !startsWith(env.QODANA_TOKEN, 'ey') }}
      shell: bash
      run: echo "Qodana is running only locally"

    - name: Code quality with Qodana Cloud
      uses: JetBrains/qodana-action@v2024.2.6
      with:
        cache-default-branch-only: ${{ inputs.cache-default-branch-only == 'true' || inputs.cache-default-branch-only == true }}
        upload-result: ${{ inputs.upload-result == 'true' || inputs.upload-result == true }}

    - name: Upload Qodana results
      uses: JavierSegoviaCordoba/reusable-workflows/actions/upload-sarif@main
      with:
        sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
