name: build-itself-kotlin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      restore-kotlin-native-cache:
        description: 'Restore Kotlin cache, `~/.konan` directory'
        default: true
        required: false
        type: boolean
    secrets:
      GRADLE_ENCRYPTION_KEY:
        required: false

env:
  GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

jobs:
  build-itself:
    if: (!contains(github.actor, '[bot]'))

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest' ]

    steps:
      - name: Checkout
        uses: JavierSegoviaCordoba/reusable-workflows/actions/checkout@main

      # TODO: Workaround for https://github.com/gradle/gradle/issues/30213?notification_referrer_id=NT_kwDOAHHijLMxMTk5Mjg4Mjg3Nzo3NDYzNTY0#issuecomment-2302398137
      - name: Cache JGit
        id: cache-jgit
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
        with:
          path: '~/.config/jgit/config'
          key: ${{ runner.os }}-jgit

      - name: Kotlin native cache
        if: inputs.restore-kotlin-native-cache == true
        uses: JavierSegoviaCordoba/reusable-workflows/actions/kotlin-native-cache@main

      - name: Set up Java
        uses: JavierSegoviaCordoba/reusable-workflows/actions/setup-java@main

      - name: Set up Gradle
        uses: JavierSegoviaCordoba/reusable-workflows/actions/setup-gradle@main
        with:
          cache-enabled: true
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-cleanup: 'on-success'

      - name: Set up Xcode
        # TODO: Fix watchOS simulator. Disable if not necessary.
        # if: 'false'
        uses: JavierSegoviaCordoba/reusable-workflows/actions/setup-xcode@main

      - name: Set up Python
        if: startsWith(matrix.os, 'macos-')
        uses: JavierSegoviaCordoba/reusable-workflows/actions/setup-python@main

      - name: Set Itself version output
        id: semver
        run: ./gradlew printSemver -P semver.stage=snapshot --githubOnlyRoot --githubOutput --no-scan

      - name: Publish next version to MavenLocal
        run: ./gradlew publishToMavenLocal -P semver.stage=snapshot

      - name: Check format
        continue-on-error: true
        run: |
          itselfVersion=${{ steps.semver.outputs.semver }}
          ./gradlew checkFormat -P itselfVersion=$itselfVersion -P semver.stage=beta

      - name: Build
        run: |
          itselfVersion=${{ steps.semver.outputs.semver }}
          ./gradlew build -P itselfVersion=$itselfVersion -P semver.stage=beta -x checkFormat -x spotlessCheck -x spotlessKotlinCheck
