name: build-itself-kotlin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      restore-kotlin-native-cache:
        description: 'Restore Kotlin cache, `~/.konan` directory'
        default: true
        required: false
        type: boolean

jobs:
  build-itself:
    if: (!contains(github.actor, '[bot]'))

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Restore Kotlin native cache
        if: ${{ inputs.restore-kotlin-native-cache == 'true' || inputs.restore-kotlin-native-cache == true }}
        uses: actions/cache@v3.3.2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Set up Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Python
        uses: actions/setup-python@v4
        if: matrix.os == 'macos-latest'
        with:
          python-version: '3.10'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0
        with:
          gradle-home-cache-cleanup: true

      - name: Set Itself version output
        id: semver
        run: ./gradlew printSemver -P semver.stage=snapshot --githubOnlyRoot --githubOutput --no-scan

      - name: Publish next version to MavenLocal
        run: ./gradlew publishToMavenLocal -P semver.stage=snapshot

      - name: Check format
        continue-on-error: true
        run: |
          itselfVersion=${{ steps.semver.outputs.semver }}
          ./gradlew checkFormat -P itselfVersion=$itselfVersion -P semver.stage=beta

      - name: Build
        run: |
          itselfVersion=${{ steps.semver.outputs.semver }}
          ./gradlew build -P itselfVersion=$itselfVersion -P semver.stage=beta -x checkFormat -x spotlessCheck -x spotlessKotlinCheck
