name: build-itself-kotlin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      tag-prefix:
        description: 'Tag prefix'
        default: ''
        required: false
        type: string
      restore-kotlin-native-cache:
        description: 'Restore Kotlin cache, `~/.konan` directory'
        default: true
        required: false
        type: boolean
      run_before_args:
        description: 'Gradle args for `Run before` step'
        default: 'null'
        required: false
        type: string
    secrets:
      GRADLE_ENCRYPTION_KEY:
        required: false

env:
  GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

jobs:
  build-itself:
    if: (!contains(github.triggering_actor, '[bot]') || github.event_name != 'pull_request')

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest' ]

    steps:
      - name: Checkout
        uses: JavierSegoviaCordoba/actions/git/checkout@main

      # TODO: Workaround for https://github.com/gradle/gradle/issues/30213?notification_referrer_id=NT_kwDOAHHijLMxMTk5Mjg4Mjg3Nzo3NDYzNTY0#issuecomment-2302398137
      - name: Cache JGit
        uses: JavierSegoviaCordoba/actions/github/cache@main
        with:
          path: '~/.config/jgit/config'
          key: '${{ runner.os }}-jgit'

      - name: Kotlin native cache
        if: inputs.restore-kotlin-native-cache == true
        uses: JavierSegoviaCordoba/actions/kotlin/cache/native@main

      - name: Set up Java
        uses: JavierSegoviaCordoba/actions/java/setup@main

      - name: Set up Gradle
        uses: JavierSegoviaCordoba/actions/gradle/setup@main
        with:
          cache-enabled: true
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-cleanup: 'on-success'

      - name: Set up Xcode
        # TODO: Fix watchOS simulator. Disable if not necessary.
        # if: 'false'
        uses: JavierSegoviaCordoba/actions/xcode/setup@main

      - name: Set up Python
        if: startsWith(matrix.os, 'macos-')
        uses: JavierSegoviaCordoba/actions/python/setup@main

      - name: Run before
        if: ${{ inputs.run_before_args != 'null' }}
        run: ${{ inputs.run_before_args }}

      - name: Set Itself version output
        id: semver
        run: ./gradlew printSemver -P semver.tagPrefix=${{ inputs.tag-prefix }} -P semver.stage=snapshot --githubOutput --no-scan -P org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled

      - name: Publish next version to MavenLocal
        run: ./gradlew publishToMavenLocal -P semver.tagPrefix=${{ inputs.tag-prefix }} -P semver.stage=snapshot --no-scan -P org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled

      - name: Check format
        continue-on-error: true
        run: |
          itselfVersion=${{ steps.semver.outputs.semver }}
          ./gradlew checkFormat -P itselfVersion=$itselfVersion -P semver.stage=beta --no-scan -P org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled

      - name: Build
        run: |
          itselfVersion=${{ steps.semver.outputs.semver }}
          ./gradlew build -P itselfVersion=$itselfVersion -P semver.stage=beta -x checkFormat -x spotlessCheck -x spotlessKotlinCheck -P org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
