name: build-changelog-renovate

on:
  workflow_call:
    inputs:
      auto-approve:
        description: 'Auto approve Renovate Pull Request'
        default: true
        required: false
        type: boolean
      renovate-branch:
        description: 'Renovate branch'
        default: 'renovate/hubdle'
        required: false
        type: string
      restore-kotlin-native-cache:
        description: 'Restore Kotlin cache, `~/.konan` directory'
        default: true
        required: false
        type: boolean
      tag-prefix:
        description: 'Tag prefix to be published'
        default: ''
        required: false
        type: string
      gradle-args:
        description: 'Gradle args for every steps'
        default: ''
        required: false
        type: string
      gradle-cache:
        description: 'Use Gradle cache'
        default: ''
        required: false
        type: string
      gradle-cache-cleanup:
        description: 'Enable removing unnecessary Gradle home cache'
        default: true
        required: false
        type: string
    secrets:
      TOKEN_GITHUB_ACTION:
        required: true

jobs:
  add-updated-dependencies-to-changelog:
    if: github.actor == 'renovate[bot]'

    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: JavierSegoviaCordoba/reusable-workflows/actions/checkout@main
        with:
          token: '${{ secrets.TOKEN_GITHUB_ACTION }}'

      - name: Kotlin native cache
        if: inputs.restore-kotlin-native-cache == true
        uses: JavierSegoviaCordoba/reusable-workflows/actions/kotlin-native-cache@main

      - name: Set up Java
        uses: JavierSegoviaCordoba/reusable-workflows/actions/setup-java@main

      - name: Set up Gradle
        uses: JavierSegoviaCordoba/reusable-workflows/actions/setup-gradle@main
        with:
          cache-enabled: ${{ inputs.gradle-cache }}
          gradle-home-cache-cleanup: ${{ inputs.gradle-cache-cleanup }}

      - name: Add updated dependencies to the CHANGELOG from Renovate
        run: ./gradlew addChangelogItem --renovateCommitTable -P semver.tagPrefix=${{ inputs.tag-prefix }} ${{ inputs.gradle-args }}

      - name: Amend commit and push
        uses: JavierSegoviaCordoba/reusable-workflows/actions/amend-commit-and-push@main

      - name: Find Pull Request
        if: ${{ (inputs.auto-approve == 'true' || inputs.auto-approve == true) }}
        id: find-pull-request
        uses: JavierSegoviaCordoba/reusable-workflows/actions/find-pull-request@main
        with:
          branch: ${{ inputs.renovate-branch }}

      - name: Auto Approve
        if: ${{ (inputs.auto-approve == 'true' || inputs.auto-approve == true) }}
        uses: JavierSegoviaCordoba/reusable-workflows/actions/auto-approve@main
        with:
          github-token: '${{ secrets.TOKEN_GITHUB_ACTION }}'
          pull-request-number: ${{ steps.find-pull-request.outputs.number }}
