name: build-changelog-renovate

on:
  workflow_call:
    inputs:
      gradle-cache:
        description: 'Use Gradle cache'
        default: true
        required: false
        type: string
    secrets:
      TOKEN_GITHUB_ACTION:
        required: true

jobs:
  add-updated-dependencies-to-changelog:
    if: github.actor == 'renovate[bot]'

    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          token: '${{ secrets.TOKEN_GITHUB_ACTION }}'

      - name: Restore Kotlin native cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Add updated dependencies to the CHANGELOG from Renovate
        uses: gradle/gradle-build-action@v2.1.3
        with:
          cache-disabled: ${{ inputs.gradle-cache == 'false' }}
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          arguments: addChangelogItem --renovateCommitTable

      - name: Commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git diff
          git add .
          git commit --amend --no-edit
          git push --force

      - name: Stop Gradle daemons
        run: ./gradlew --stop
