name: build-changelog-renovate

on:
  workflow_call:
    inputs:
      auto-approve:
        description: 'Auto approve Renovate Pull Request'
        default: true
        required: false
        type: boolean
      restore-kotlin-native-cache:
        description: 'Restore Kotlin cache, `~/.konan` directory'
        default: true
        required: false
        type: boolean
      tag-prefix:
        description: 'Tag prefix to be published'
        default: ''
        required: false
        type: string
      gradle-args:
        description: 'Gradle args for every steps'
        default: ''
        required: false
        type: string
      gradle-cache:
        description: 'Use Gradle cache'
        default: ''
        required: false
        type: string
      gradle-cache-cleanup:
        description: 'Enable removing unnecessary Gradle home cache'
        default: true
        required: false
        type: string
    secrets:
      TOKEN_GITHUB_ACTION:
        required: true

jobs:
  add-updated-dependencies-to-changelog:
    if: github.actor == 'renovate[bot]'

    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          token: '${{ secrets.TOKEN_GITHUB_ACTION }}'

      - name: Restore Kotlin native cache
        if: ${{ inputs.restore-kotlin-native-cache == 'true' || inputs.restore-kotlin-native-cache == true }}
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Set up Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2.10.0
        with:
          cache-disabled: ${{ inputs.gradle-cache == 'false' }}
          gradle-home-cache-cleanup: ${{ inputs.gradle-cache-cleanup == 'true' }}

      - name: Add updated dependencies to the CHANGELOG from Renovate
        run: ./gradlew addChangelogItem --renovateCommitTable -P semver.tagPrefix=${{ inputs.tag-prefix }} ${{ inputs.gradle-args }}

      - name: Commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git diff
          git add .
          git commit --amend --no-edit
          git push --force

      - name: Find Pull Request
        if: ${{ (inputs.auto-approve == 'true' || inputs.auto-approve == true) }}
        id: find-pull-request
        uses: juliangruber/find-pull-request-action@3a4c7c62101755c3778d397dcb6a760a558992f1 # v1.8.0
        with:
          branch: renovate/hubdle

      - name: Auto Approve
        if: ${{ (inputs.auto-approve == 'true' || inputs.auto-approve == true) }}
        uses: hmarr/auto-approve-action@44888193675f29a83e04faf4002fa8c0b537b1e4 # v3.2.1
        with:
          github-token: '${{ secrets.TOKEN_GITHUB_ACTION }}'
          pull-request-number: ${{ steps.find-pull-request.outputs.number }}
          review-message: "Auto approved"
