name: build-itself-kotlin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      restore-kotlin-native-cache:
        description: 'Restore Kotlin cache, `~/.konan` directory'
        default: true
        required: false
        type: boolean

jobs:
  build-itself:
    if: (!contains(github.actor, '[bot]'))

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Restore Kotlin native cache
        if: ${{ inputs.restore-kotlin-native-cache == 'true' || inputs.restore-kotlin-native-cache == true }}
        uses: actions/cache@v3.3.1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Set up Java
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.6.1
        with:
          gradle-home-cache-cleanup: true

      - name: Set Itself version output
        id: semver
        run: ./gradlew printSemver -Psemver.stage=snapshot --githubOnlyRoot --githubOutput --no-scan

      - name: Publish next version to MavenLocal
        run: ./gradlew publishToMavenLocal -Psemver.stage=snapshot

      - name: Check format
        continue-on-error: true
        run: |
          itselfVersion=${{ steps.semver.outputs.semver }}
          ./gradlew checkFormat -PitselfVersion=$itselfVersion -Psemver.stage=beta

      - name: Build
        run: |
          itselfVersion=${{ steps.semver.outputs.semver }}
          ./gradlew build -PitselfVersion=$itselfVersion -Psemver.stage=beta -x checkFormat -x spotlessCheck -x spotlessKotlinCheck
