name: build-kotlin-jvm

on:
  workflow_call:
    inputs:
      args:
        description: 'Gradle args for `build` step'
        default: ''
        required: false
        type: string
    secrets:
      OSS_USER:
        required: true
      OSS_TOKEN:
        required: true
      OSS_STAGING_PROFILE_ID:
        required: true

jobs:
  jvm:
    if: github.actor != 'renovate[bot]'

    runs-on: ubuntu-latest

    env:
      OSS_USER: '${{ secrets.OSS_USER }}'
      OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
      OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-{{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Increment version
        run: ./gradlew reckonTagCreate -P"reckon.stage"="final"

      - name: Gradle build
        if: ${{ always() }}
        run: ./gradlew build ${{ inputs.args }} -P"reckon.stage"="snapshot" -P"reckon.scope"="patch"

      - name: Generate code analysis reports
        if: ${{ always() }}
        run: ./gradlew detekt -P"reckon.stage"="snapshot" -P"reckon.scope"="patch"

      - name: Upload code analysis reports
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'build/reports/detekt/detekt.sarif'

      - name: Generate docs
        if: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}
        run: ./gradlew buildDocs -P"reckon.stage"="snapshot" -P"reckon.scope"="patch"

      - name: Publish snapshot
        if: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}
        run: ./gradlew publishToSonatype -P"reckon.stage"="snapshot" -P"reckon.scope"="patch"

      - name: Deploy snapshot docs to Github Pages
        if: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: 'gh-pages'
          folder: 'build/docs/_site'
          clean: false
          single-commit: true

      - name: Stop Gradle daemons
        run: ./gradlew --stop
