name: build-itself-kotlin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      restore-kotlin-native-cache:
        description: 'Restore Kotlin cache, `~/.konan` directory'
        default: true
        required: false
        type: boolean

jobs:
  build-itself:
    if: (!contains(github.actor, '[bot]'))

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-14', 'ubuntu-latest' ]

    steps:
      - name: Checkout
        uses: JavierSegoviaCordoba/reusable-workflows/actions/checkout@main

      - name: Validate Gradle wrapper
        uses: JavierSegoviaCordoba/reusable-workflows/actions/gradle-wrapper-validation@main

      - name: Kotlin native cache
        if: inputs.restore-kotlin-native-cache == true
        uses: JavierSegoviaCordoba/reusable-workflows/actions/kotlin-native-cache@main

      - name: Set up Java
        uses: JavierSegoviaCordoba/reusable-workflows/actions/setup-java@main

      - name: Set up Gradle
        uses: JavierSegoviaCordoba/reusable-workflows/actions/setup-gradle@main
        with:
          cache-enabled: true
          gradle-home-cache-cleanup: true

      - name: Set up Xcode
        # TODO: Fix watchOS simulator. Disable if not necessary.
        # if: 'false'
        uses: JavierSegoviaCordoba/reusable-workflows/actions/setup-xcode@main

      - name: Set up Python
        if: startsWith(matrix.os, 'macos-')
        uses: JavierSegoviaCordoba/reusable-workflows/actions/setup-python@main

      - name: Set Itself version output
        id: semver
        run: ./gradlew printSemver -P semver.stage=snapshot --githubOnlyRoot --githubOutput --no-scan

      - name: Publish next version to MavenLocal
        run: ./gradlew publishToMavenLocal -P semver.stage=snapshot

      - name: Check format
        continue-on-error: true
        run: |
          itselfVersion=${{ steps.semver.outputs.semver }}
          ./gradlew checkFormat -P itselfVersion=$itselfVersion -P semver.stage=beta

      - name: Build
        run: |
          itselfVersion=${{ steps.semver.outputs.semver }}
          ./gradlew build -P itselfVersion=$itselfVersion -P semver.stage=beta -x checkFormat -x spotlessCheck -x spotlessKotlinCheck
