name: dump-api

on:
  workflow_call:
    inputs:
      restore-kotlin-native-cache:
        description: 'Restore Kotlin cache, `~/.konan` directory'
        default: true
        required: false
        type: boolean
      gradle-cache:
        description: 'Use Gradle cache'
        default: true
        required: false
        type: string
      gradle-cache-cleanup:
        description: 'Enable removing unnecessary Gradle home cache'
        default: true
        required: false
        type: string
    secrets:
      GRADLE_ENCRYPTION_KEY:
        required: false
      TOKEN_GITHUB_ACTION:
        required: true

env:
  GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

jobs:
  dump-api:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: JavierSegoviaCordoba/actions/git/checkout@main
        with:
          token: '${{ secrets.TOKEN_GITHUB_ACTION }}'

      # TODO: Workaround for https://github.com/gradle/gradle/issues/30213?notification_referrer_id=NT_kwDOAHHijLMxMTk5Mjg4Mjg3Nzo3NDYzNTY0#issuecomment-2302398137
      - name: Cache JGit
        uses: JavierSegoviaCordoba/actions/github/cache@main
        with:
          path: '~/.config/jgit/config'
          key: '${{ runner.os }}-jgit'

      - name: Kotlin native cache
        if: inputs.restore-kotlin-native-cache == true
        uses: JavierSegoviaCordoba/actions/kotlin/cache/native@main

      - name: Set up Java
        uses: JavierSegoviaCordoba/actions/java/setup@main

      - name: Set up Gradle
        uses: JavierSegoviaCordoba/actions/gradle/setup@main
        with:
          cache-enabled: ${{ inputs.gradle-cache }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-cleanup: ${{ inputs.gradle-cache-cleanup }}

      - name: Dump API
        run: ./gradlew dumpApi -P org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled

      - name: Amend commit and push
        uses: JavierSegoviaCordoba/actions/git/commit@main
        with:
          amend: true
          push: true
          force: true
