name: generate-version-tag

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      stage:
        description: 'Stage [alpha, beta, rc, final, auto]'
        default: 'auto'
        required: true
        type: string
      scope:
        description: 'Scope [patch, minor, major, auto]'
        default: 'auto'
        required: true
        type: string
      gradle-cache:
        description: 'Use Gradle cache'
        default: true
        required: false
        type: string
    secrets:
      TOKEN_GITHUB_ACTION:
        required: true

jobs:
  generate-version-tag:
    if: ((inputs.allow-github-actor-bots == true) || (!contains(github.actor, '[bot]')))

    runs-on: 'macos-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          token: '${{ secrets.TOKEN_GITHUB_ACTION }}'

      - name: Restore Kotlin native cache
        uses: actions/cache@v3.0.4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.2.1
        with:
          cache-disabled: ${{ inputs.gradle-cache == 'false' }}

      - name: Build
        run: ./gradlew build -Psemver.stage=${{ inputs.stage }} -Psemver.scope=${{ inputs.scope }}

      - name: Set semver as output
        id: semver
        run: ./gradlew printSemver --githubOnlyRoot --githubOutput -Psemver.stage=${{ inputs.stage }} -Psemver.scope=${{ inputs.scope }} -Psemver.checkClean=false

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

      - name: Patch Changelog and regenerate README badges
        run: ./gradlew patchChangelog mergeChangelog writeReadmeBadges -Psemver.stage=${{ inputs.stage }} -Psemver.scope=${{ inputs.scope }} -Psemver.checkClean=false

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff
          git add .
          git commit -m "Publish ${{ steps.semver.outputs.semver }}" -a

      - name: Generate Tag
        run: ./gradlew createSemverTag -Psemver.stage=${{ inputs.stage }} -Psemver.scope=${{ inputs.scope }}

      - name: Push
        run: git push --follow-tags

      - name: Stop Gradle daemons
        run: ./gradlew --stop
