name: generate-version-tag

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      stage:
        description: 'Stage [alpha, beta, rc, final, auto]'
        default: 'auto'
        required: true
        type: string
      scope:
        description: 'Scope [patch, minor, major, auto]'
        default: 'auto'
        required: true
        type: string
      restore-kotlin-native-cache:
        description: 'Restore Kotlin cache, `~/.konan` directory'
        default: true
        required: false
        type: boolean
      gradle-cache:
        description: 'Use Gradle cache'
        default: true
        required: false
        type: string
      gradle-cache-cleanup:
        description: 'Enable removing unnecessary Gradle home cache'
        default: true
        required: false
        type: string
    secrets:
      SIGNING_GNUPG_KEY:
        required: false
      SIGNING_GNUPG_PASSPHRASE:
        required: false
      TOKEN_GITHUB_ACTION:
        required: true

env:
  SIGNING_GNUPG_KEY: '${{ secrets.SIGNING_GNUPG_KEY }}'
  SIGNING_GNUPG_PASSPHRASE: '${{ secrets.SIGNING_GNUPG_PASSPHRASE }}'

jobs:
  generate-version-tag:
    if: ((inputs.allow-github-actor-bots == true) || (!contains(github.actor, '[bot]')))

    runs-on: 'macos-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0
          token: '${{ secrets.TOKEN_GITHUB_ACTION }}'

      - name: Restore Kotlin native cache
        if: ${{ inputs.restore-kotlin-native-cache == 'true' }}
        uses: actions/cache@v3.2.0
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Set up Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          cache-disabled: ${{ inputs.gradle-cache == 'false' }}
          gradle-home-cache-cleanup: ${{ inputs.gradle-cache-cleanup == 'true' }}

      # TODO: Fix watchOS simulator. Remove when Kotlin 1.8.0 is released
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4.1'

      - name: Build
        run: ./gradlew build -Psemver.stage=${{ inputs.stage }} -Psemver.scope=${{ inputs.scope }}

      - name: Set semver as output
        id: semver
        run: ./gradlew printSemver --githubOnlyRoot --githubOutput -Psemver.stage=${{ inputs.stage }} -Psemver.scope=${{ inputs.scope }} -Psemver.checkClean=false

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v3.1.1
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

      - name: Patch Changelog and regenerate README badges
        run: ./gradlew patchChangelog mergeChangelog writeReadmeBadges -Psemver.stage=${{ inputs.stage }} -Psemver.scope=${{ inputs.scope }} -Psemver.checkClean=false

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff
          git add .
          git commit -m "Publish ${{ steps.semver.outputs.SEMVER }}" -a

      - name: Generate Tag
        run: ./gradlew createSemverTag -Psemver.stage=${{ inputs.stage }} -Psemver.scope=${{ inputs.scope }}

      - name: Push
        run: git push --follow-tags
