name: upgrade-gradle-wrapper

on:
  workflow_call:
    inputs:
      restore-kotlin-native-cache:
        description: 'Restore Kotlin cache, `~/.konan` directory'
        default: true
        required: false
        type: boolean
      gradle-cache:
        description: 'Use Gradle cache'
        default: true
        required: false
        type: string
      gradle-cache-cleanup:
        description: 'Enable removing unnecessary Gradle home cache'
        default: true
        required: false
        type: string
      previous-gradle-version:
        description: 'Gradle Wrapper version to upgrade'
        required: true
        type: string
      gradle-version:
        description: 'Gradle Wrapper version to upgrade'
        required: true
        type: string
      update-changelog:
        description: 'Add the changelog entry for the new version if the commit is from Renovate'
        default: true
        required: false
        type: boolean
    secrets:
      TOKEN_GITHUB_ACTION:
        required: true

jobs:
  upgrade-gradle-wrapper:
    runs-on: 'ubuntu-latest'
    if: contains(github.ref, 'renovate')

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          token: '${{ secrets.TOKEN_GITHUB_ACTION }}'

      - name: Restore Kotlin native cache
        if: ${{ inputs.restore-kotlin-native-cache == 'true' || inputs.restore-kotlin-native-cache == true }}
        uses: actions/cache@v3.3.2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Set up Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0
        with:
          cache-disabled: ${{ inputs.gradle-cache == 'false' }}
          gradle-home-cache-cleanup: ${{ inputs.gradle-cache-cleanup == 'true' }}

      - name: Reset current branch to main
        run: git reset --hard HEAD~1

      - name: Upgrade Gradle Wrapper
        run: |
          ./gradlew wrapper --gradle-version=${{ inputs.gradle-version }}
          ./gradlew wrapper --gradle-version=${{ inputs.gradle-version }}

      - name: Git commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git diff
          git add .
          git commit -m "Update dependency gradle to v8.5" -m "| datasource     | package | from | to  |\n| -------------- | ------- | ---- | --- |\n| gradle-version | gradle  | ${inputs.previous-gradle-version} | ${inputs.gradle-version} |"

      - name: Add updated dependencies to the CHANGELOG from Renovate
        if: ${{ inputs.update-changelog == true }}
        run: ./gradlew addChangelogItem --renovateCommitTable

      - name: Git push
        run: |
          git log -n 3
#          git push
