name: 'Gradle Wrapper Validation'

description: 'Action for validating Gradle wrapper'

runs:
  using: "composite"

  steps:
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@b231772637bb498f11fdbc86052b6e8a8dc9fc92 # v2
